name: confluent-docker-utils
lang: unknown
lang_version: unknown
renovatebot:
  enable: true
  automerge:
    enable: true
git:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
code_artifact:
  enable: true
  package_paths:
    - pypi-internal/pypi//confluent-docker-utils
